### ISSUE TITLE
Crashes complaining about invalid memory address

### ISSUE THREAD

**Issue by LillyWho** [jondot/groundcontrol#35]
Terminal output is as follows:

`sudo ./groundcontrol -config groundcontrol.json
2019/12/01 11:55:21 Reporters: No TempoDB credentials, skipping.
2019/12/01 11:55:21 Reporters: Librato OK.
2019/12/01 11:55:21 Lauching Health
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x12ac4]

goroutine 1 [running]:
main.(*LibratoReporter).ReportHealth(0x10474540, 0x10472340)
        /Users/dotan/projects/groundcontrol/librato_reporter.go:55 +0x5a4
main.report(0x10475230, 0x104744e0)
        /Users/dotan/projects/groundcontrol/main.go:105 +0x15c
main.main()
        /Users/dotan/projects/groundcontrol/main.go:76 +0xb98`

Doesn't sound like a configuration issue, so I guess it's something to be fixed in the code. (Not running as sudo throws the same error, btw.)

Raspberry Pi 2B
Ubuntu Mate 18.04.2

**Comment by benjaminlcy** [comment]
same here
